/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;

import DB.DB_Cliente;
import DB.DB_Funcionario;
import DB.DB_Ingreso;
import DB.DB_Producto;
import DB.DB_manager;
import Entities.M_cliente;
import Entities.M_facturaCabecera;
import Entities.M_funcionario;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Ramiro Ferreira
 */
public class POSTTS extends javax.swing.JInternalFrame {

    /**
     * Creates new form POSTTS
     */
    public POSTTS() {
        initComponents();
        test();
    }

    public void test() {
//        try {
//            DB_manager.conectarBD("postgres", "postgres");
//        } catch (SQLException ex) {
//            Logger.getLogger(POSTTS.class.getName()).log(Level.SEVERE, null, ex);
//        }
        Vector productoCategoria = DB_manager.obtenerCategoria();
        JPanel jpCategoira = new JPanel(new MigLayout());
        double largo = 0;
        int longitud = Math.round(Math.round(productoCategoria.size() * 0.5)) - 1;
        Insets inset = new Insets(25, 10, 25, 10);
        for (int i = 0; i < productoCategoria.size(); i++) {
            JButton jbCategoria = new JButton(productoCategoria.get(i).toString());
            jbCategoria.addActionListener(new ButtonHandler());
            jbCategoria.setMargin(inset);
            if (i == longitud) {
                jpCategoira.add(jbCategoria, "wrap");
            } else {
                jpCategoira.add(jbCategoria);
            }
        }
        this.jScrollPane1.setViewportView(jpCategoira);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCliente = new javax.swing.JButton();
        jbPagar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbMozo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbTeclado = new javax.swing.JButton();
        jpGrupos = new javax.swing.JPanel();
        jbGroupLeft = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbGroupRight = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        jbGroupLeft1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jbGroupRight1 = new javax.swing.JButton();
        jpDetalle = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Punto de venta");
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setLayout(new java.awt.GridLayout(2, 3, 1, 1));

        jbCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCliente.setText("Cliente");
        jPanel1.add(jbCliente);

        jbPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbPagar.setText("Pagar");
        jbPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jbPagar);

        jbCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancelar);

        jbMozo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbMozo.setText("Mozo");
        jPanel1.add(jbMozo);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jbTeclado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbTeclado.setText("Teclado");
        jPanel1.add(jbTeclado);

        jpGrupos.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));
        jpGrupos.setLayout(new java.awt.BorderLayout());

        jbGroupLeft.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbGroupLeft.setText("<--");
        jbGroupLeft.setPreferredSize(new java.awt.Dimension(100, 200));
        jbGroupLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGroupLeftActionPerformed(evt);
            }
        });
        jpGrupos.add(jbGroupLeft, java.awt.BorderLayout.WEST);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jpGrupos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbGroupRight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbGroupRight.setText("-->");
        jbGroupRight.setPreferredSize(new java.awt.Dimension(100, 200));
        jbGroupRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGroupRightActionPerformed(evt);
            }
        });
        jpGrupos.add(jbGroupRight, java.awt.BorderLayout.EAST);

        jpProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jpProductos.setLayout(new java.awt.BorderLayout());

        jbGroupLeft1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbGroupLeft1.setText("<--");
        jbGroupLeft1.setPreferredSize(new java.awt.Dimension(100, 200));
        jbGroupLeft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGroupLeft1ActionPerformed(evt);
            }
        });
        jpProductos.add(jbGroupLeft1, java.awt.BorderLayout.WEST);
        jpProductos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jbGroupRight1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbGroupRight1.setText("-->");
        jbGroupRight1.setPreferredSize(new java.awt.Dimension(100, 200));
        jpProductos.add(jbGroupRight1, java.awt.BorderLayout.EAST);

        jpDetalle.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cant.", "Precio", "Subtotal"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jpDetalle.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(552, 200));
        jPanel6.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total");
        jPanel6.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("0");
        jPanel6.add(jTextField1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel5);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente");
        jPanel6.add(jLabel3);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("Barra");
        jPanel6.add(jTextField3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mozo");
        jPanel6.add(jLabel4);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setText("Mozo1");
        jPanel6.add(jTextField4);

        jpDetalle.add(jPanel6, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jpGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGroupLeft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGroupLeft1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGroupLeft1ActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPagarActionPerformed

    private void jbGroupLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGroupLeftActionPerformed
        int value = this.jScrollPane1.getHorizontalScrollBar().getValue();
        if ((value - 100) < this.jScrollPane1.getHorizontalScrollBar().getMinimum()) {
            this.jScrollPane1.getHorizontalScrollBar().setValue(this.jScrollPane1.getHorizontalScrollBar().getMinimum());
        } else {
            this.jScrollPane1.getHorizontalScrollBar().setValue(value - 100);
        }
    }//GEN-LAST:event_jbGroupLeftActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbGroupRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGroupRightActionPerformed
        int value = this.jScrollPane1.getHorizontalScrollBar().getValue();
        if ((value + 100) > this.jScrollPane1.getHorizontalScrollBar().getMaximum()) {
            this.jScrollPane1.getHorizontalScrollBar().setValue(this.jScrollPane1.getHorizontalScrollBar().getMaximum());
        } else {
            this.jScrollPane1.getHorizontalScrollBar().setValue(value + 100);
        }
    }//GEN-LAST:event_jbGroupRightActionPerformed

    public class ButtonHandler implements ActionListener {

        //This method is called in case an action event occurs.For example you click on the
        //button      
        public void actionPerformed(ActionEvent event) {
            System.out.println(event.getActionCommand());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCliente;
    private javax.swing.JButton jbGroupLeft;
    private javax.swing.JButton jbGroupLeft1;
    private javax.swing.JButton jbGroupRight;
    private javax.swing.JButton jbGroupRight1;
    private javax.swing.JButton jbMozo;
    private javax.swing.JButton jbPagar;
    private javax.swing.JButton jbTeclado;
    private javax.swing.JPanel jpDetalle;
    private javax.swing.JPanel jpGrupos;
    private javax.swing.JPanel jpProductos;
    // End of variables declaration//GEN-END:variables
}
